<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="0" total="6" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-05-05T16:23:36 CEST" name="Suite" finished-at="2025-05-05T16:24:53 CEST" duration-ms="77414">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorValidationTest.loginErrorValidation()[pri:0, instance:practiceSeleniumFramework.tests.ErrorValidationTest@3b35a229]" name="loginErrorValidation" class="practiceSeleniumFramework.tests.ErrorValidationTest"/>
        <method signature="ErrorValidationTest.productErrorValidation()[pri:0, instance:practiceSeleniumFramework.tests.ErrorValidationTest@3b35a229]" name="productErrorValidation" class="practiceSeleniumFramework.tests.ErrorValidationTest"/>
      </group> <!-- ErrorHandling -->
      <group name="Purchase">
        <method signature="SubmitOrderTest.SubmitOrder(java.util.HashMap)[pri:0, instance:practiceSeleniumFramework.tests.SubmitOrderTest@740fb309]" name="SubmitOrder" class="practiceSeleniumFramework.tests.SubmitOrderTest"/>
      </group> <!-- Purchase -->
    </groups>
    <test started-at="2025-05-05T16:23:36 CEST" name="Error Validation Test" finished-at="2025-05-05T16:23:50 CEST" duration-ms="14693">
      <class name="practiceSeleniumFramework.tests.ErrorValidationTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:practiceSeleniumFramework.tests.ErrorValidationTest@3b35a229]" started-at="2025-05-05T16:23:36 CEST" name="launchApplication" finished-at="2025-05-05T16:23:43 CEST" duration-ms="7637" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="loginErrorValidation()[pri:0, instance:practiceSeleniumFramework.tests.ErrorValidationTest@3b35a229]" started-at="2025-05-05T16:23:43 CEST" name="loginErrorValidation" finished-at="2025-05-05T16:23:44 CEST" duration-ms="897" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:practiceSeleniumFramework.tests.ErrorValidationTest@3b35a229]" started-at="2025-05-05T16:23:44 CEST" name="tearDown" finished-at="2025-05-05T16:23:44 CEST" duration-ms="83" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:practiceSeleniumFramework.tests.ErrorValidationTest@3b35a229]" started-at="2025-05-05T16:23:44 CEST" name="launchApplication" finished-at="2025-05-05T16:23:49 CEST" duration-ms="4342" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="productErrorValidation()[pri:0, instance:practiceSeleniumFramework.tests.ErrorValidationTest@3b35a229]" started-at="2025-05-05T16:23:49 CEST" name="productErrorValidation" finished-at="2025-05-05T16:23:50 CEST" duration-ms="1030" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "org.openqa.selenium.WebElement.findElement(org.openqa.selenium.By)" because "prod" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.WebElement.findElement(org.openqa.selenium.By)" because "prod" is null
at practiceSeleniumFramework.pageObjects.ProductCataloguePage.addProductToCart(ProductCataloguePage.java:46)
at practiceSeleniumFramework.tests.ErrorValidationTest.productErrorValidation(ErrorValidationTest.java:38)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- productErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:practiceSeleniumFramework.tests.ErrorValidationTest@3b35a229]" started-at="2025-05-05T16:23:50 CEST" name="tearDown" finished-at="2025-05-05T16:23:50 CEST" duration-ms="149" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- practiceSeleniumFramework.tests.ErrorValidationTest -->
    </test> <!-- Error Validation Test -->
    <test started-at="2025-05-05T16:23:36 CEST" name="Submit Order Test" finished-at="2025-05-05T16:24:53 CEST" duration-ms="77414">
      <class name="practiceSeleniumFramework.tests.SubmitOrderTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:practiceSeleniumFramework.tests.SubmitOrderTest@740fb309]" started-at="2025-05-05T16:23:36 CEST" name="launchApplication" finished-at="2025-05-05T16:23:44 CEST" duration-ms="7192" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="SubmitOrder(java.util.HashMap)[pri:0, instance:practiceSeleniumFramework.tests.SubmitOrderTest@740fb309]" started-at="2025-05-05T16:23:44 CEST" name="SubmitOrder" data-provider="getData" finished-at="2025-05-05T16:24:08 CEST" duration-ms="24264" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Sravani@1410, email=sravanisravs1410@gmail.com, productName=ZARA COAT 3}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Item not found expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Item not found expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at practiceSeleniumFramework.tests.SubmitOrderTest.SubmitOrder(SubmitOrderTest.java:37)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SubmitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:practiceSeleniumFramework.tests.SubmitOrderTest@740fb309]" started-at="2025-05-05T16:24:08 CEST" name="tearDown" finished-at="2025-05-05T16:24:08 CEST" duration-ms="109" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:practiceSeleniumFramework.tests.SubmitOrderTest@740fb309]" started-at="2025-05-05T16:24:08 CEST" name="launchApplication" finished-at="2025-05-05T16:24:13 CEST" duration-ms="5234" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="SubmitOrder(java.util.HashMap)[pri:0, instance:practiceSeleniumFramework.tests.SubmitOrderTest@740fb309]" started-at="2025-05-05T16:24:13 CEST" name="SubmitOrder" data-provider="getData" finished-at="2025-05-05T16:24:29 CEST" duration-ms="15819" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Sravani@1410, email=sravanisravs1410@gmail.com, productName=ZARA COAT 3}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SubmitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:practiceSeleniumFramework.tests.SubmitOrderTest@740fb309]" started-at="2025-05-05T16:24:29 CEST" name="tearDown" finished-at="2025-05-05T16:24:29 CEST" duration-ms="139" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:practiceSeleniumFramework.tests.SubmitOrderTest@740fb309]" started-at="2025-05-05T16:24:29 CEST" name="launchApplication" finished-at="2025-05-05T16:24:32 CEST" duration-ms="2575" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="SubmitOrder(java.util.HashMap)[pri:0, instance:practiceSeleniumFramework.tests.SubmitOrderTest@740fb309]" started-at="2025-05-05T16:24:32 CEST" name="SubmitOrder" data-provider="getData" finished-at="2025-05-05T16:24:47 CEST" duration-ms="15628" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Sravanisai@22, email=methukulasravani@gmail.com, productName=ADIDAS ORIGINAL}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SubmitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:practiceSeleniumFramework.tests.SubmitOrderTest@740fb309]" started-at="2025-05-05T16:24:47 CEST" name="tearDown" finished-at="2025-05-05T16:24:48 CEST" duration-ms="303" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:practiceSeleniumFramework.tests.SubmitOrderTest@740fb309]" started-at="2025-05-05T16:24:48 CEST" name="launchApplication" finished-at="2025-05-05T16:24:52 CEST" duration-ms="4412" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="OrderHistoryTest()[pri:0, instance:practiceSeleniumFramework.tests.SubmitOrderTest@740fb309]" started-at="2025-05-05T16:24:52 CEST" name="OrderHistoryTest" finished-at="2025-05-05T16:24:53 CEST" depends-on-methods="practiceSeleniumFramework.tests.SubmitOrderTest.SubmitOrder" duration-ms="918" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OrderHistoryTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:practiceSeleniumFramework.tests.SubmitOrderTest@740fb309]" started-at="2025-05-05T16:24:53 CEST" name="tearDown" finished-at="2025-05-05T16:24:53 CEST" duration-ms="119" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- practiceSeleniumFramework.tests.SubmitOrderTest -->
    </test> <!-- Submit Order Test -->
  </suite> <!-- Suite -->
</testng-results>
